name: Build and Run Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: my-app:latest
          load: true

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name my_app_container my-app:latest

      - name: Verify application is running
        run: |
          sleep 10
          curl --fail http://localhost:8000/api/v1/health || (docker logs my_app_container && exit 1)
